# Generated by Django 4.2 on 2024-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
